README.md, wit/deps/io/poll.wit, wit/deps/io/streams.wit, wit/deps/logging/handler.wit, wit/deps/poll/poll.wit, wit/deps/random/random.wit, wit/incoming-handler.wit, wit/outgoing-handler.wit, wit/proxy.wit, wit/types.wit
This PR proposes some initial Wit interfaces and a `wasi:http/proxy` world using them that's mostly a synthesis of a lot of the existing proposals.  As the proposal develops, I expect us to add new "bigger" worlds than `wasi:http/proxy` world (either here or in other proposals), but this `wasi:http/proxy` world seems like perhaps a good minimal concrete starting point.  There's still a lot more to fill in to make this a proper WASI proposal, but perhaps this is enough for us to chew on now.  Lastly, I still consider this very much in a draft state so happy to iterate with folks in this PR.
(cc @PiotrSikora @brendandburns @eduardomourar)
=> add Wit interfaces

wit/types.wit
It's missing, as pointed out in #10.
This PR brings back some earlier question I had when sketching the initial Wit which I might as well ask since we're in the area:
* Should the request constructor take a single `record` so that the fields are named instead of relying on, in most languages, nameless positional order.
* Should there also be an option to create/consume the {scheme,authority,path,query} fields via single URL?  It does make more URL parsing work for the host (although it seems likely that this code would already be present in the underlying library anyways), but it may factor it out of the guest and may save number-of-hostcalls.  If so, in the request constructor, is the best way to express this as a variant taking either the above record and URL as two cases?
=> add query field

wit/types.wit
As discussed in #11.  `path-and-query` is made optional as well.  `scheme` was already optional, but `authority` was not, so I made it optional too b/c I think the same rationale applies, but lmk if not.
=> Remove 'query', rename 'path' to 'path-with-query'

README.md, wit/deps.lock, wit/deps.toml, wit/deps/io/world.wit, wit/deps/logging/world.wit, wit/deps/poll/world.wit, wit/deps/random/world.wit
This PR uses @rvolosatovs's [`depit`](https://github.com/rvolosatovs/depit) tool to automate the currently-manual steps of copying the Wit documents from other WASI proposal repos.  (Thanks Roman!)  Over time we expect this tooling to evolve further, but this seems like a pretty useful and super-easy-to-adopt short-term improvement.
@Mossaka I think this also goes a long way to addressing the concerns about manual duplication in #20, so I think it resolves that issue too?
(The `world.wit` files are added by actually running `depit` before committing; everything else was in sync already.)
cc @pchickey @sunfishcode @peterhuene
=> Use `wit-dep` tool to automatically manage dependency vendoring

.github/workflows/main.yml
This PR adds a GH Action to check if deps are up-to-date. It can also verify all the wit-abis if they are updated to use the newest wit package syntax.
=> Add CI check to veirfy deps are up-to-date

wit/types.wit
=> Add comment regarding header/trailer sharing

proxy.md, wit/handler.wit, wit/types.wit
Convert all pseudo-resources to full resources, and as such introduces some `borrow<..>` annotations.
Additionally, this reworks body handling to go through an intermediate resource, rather than expose direct access to the underlying stream for the request/response resource. This intermediate resource allows us to better track when trailers are expected to be written or read.
=> Use resources in wasi-http

proxy.md, wit/handler.wit, wit/proxy.wit, wit/types.wit
In addition to adding a lot of documentation, this PR takes the liberty of defining new type aliases `field-key` and
`field-value`, which make writing the docs for `fields` a lot clearer.
=> Big improvements to doc comments

proxy.md, wit/types.wit
Prior to this PR, the `outgoing-request` and `outgoing-response` resources have methods `write` which return `result<outgoing-body>`.
`body` is a better name than `write` - it makes it explicit this is about access to a body resource. The `outgoing-body` resource itself has a method `write` which gives the body contents as a stream. Using different names for these closely related but different methods makes their distinction more clear.
Additionally: the docs for `outgoing-request.write` were incorrect - the returned `outgoing-body` is not a child of the `outgoing-request` (or `outgoing-response`). If we were to enforce a child relationship here, outgoing body streaming (i.e. writing to the body after the request or response has been initiated) would not be possible. The word `child` had …
=> Rename the methods to retrieve `outgoing-body` from `write` to `body`

proxy.md, wit/types.wit
This PR includes a number of changes that we've discussed independently, all bundled up into one:
* The `request-options` record has been turned into a resource, which allows for two new capabilities: embedders can clearly indicate when timeouts are not supported by returning `None` from a setter; the spec can evolve without breaking older guests, as new methods can be added without breaking compatibility.
* The `response-outparam.set` method has had its result type removed. In general the intent is that any validation of the status code and headers should occur before `set` is called, and that validation was the only need for the result return type.
* The `future-trailers.get` method now returns an `option<trailers>` value on success, which allows for the presence of trailers in hte …
=> Fields, timeout, and incoming handler signature changes

proxy.md, wit/types.wit
As the setters for `outgoing-request` and `outgoing-response` take argument values that are potentially malformed, allow all setters to reject invalid inputs. This necessitated removing some constructor arguments, as wit currently does not allow for constructors to fail, replacing them instead with documented sensible defaults.
Additionally, as the `fields.delete` method is mutating the fields, change its return type to also permit a `forbidden` error.
=> Fallible setters, and fields.delete method

proxy.md, wit/handler.wit, wit/types.wit
As discussed in #49, this PR replaces the current placeholder `error` variant cases with the error types enumerated by [RFC 9209](https://www.rfc-editor.org/rfc/rfc9209#name-proxy-error-types) which are maintained in an [IANA table](https://www.iana.org/assignments/http-proxy-status/http-proxy-status.xhtml#table-http-proxy-error-types).  Note that these specs also specify payloads for some of these error cases which I also reflected in the `error` case payloads.
The one interesting bit of minutiae, where I'm going with [Adam's suggestion](https://github.com/WebAssembly/wasi-http/issues/49#issuecomment-1693858871), but I have no strong opinions about so happy to hear arguments to the contrary, is that there is no `error` case corresponding to `http_request_error`, as this seems like it …
=> Fill in the 'error' variant

proxy.md, wit/types.wit
And update the doc strings throughout to specify which give a mutable fields and which give an immutable fields. also, add missed text that a future-trailers gives a child resource fields.
One of the major motivators of this change is eliminating the possibility of modifying a `Content-Length` header after an outgoing body has been created. We expect it is impossible to satisfy changes to content-length once the body is being sent, so rather than specify what the behavior of that particular problem, lets just make the fields immutable so that it is always rejected at the call to `set`, `append`, or `delete`.
=> all child fields are immutable, add header-error.immutable error

proxy.md, wit/types.wit
`outgoing-body.finish` now fails if the body's `outgoing-request` or `outgoing-response` was constructed with a Content-Length header, and the contents written to the body (via `write`) does not match the value given in the Content-Length.
=> make outgoing-body.finish fallible in case of a Content-Length mismatch

README.md
As discussed in today's WASI Subgroup meeting, based on @guybedford's presentation, a meaningful second implementation of this proposal (beyond a pure-wasm runtime like Wasmtime and WasmEdge) would be Node.js (or Deno or Bun), running a `wasi:http/proxy`-targeting component directly, implemented in terms of their existing C++ HTTP implementations.  In the short-term, this embedding can be implemented via JS glue code (leveraging [jco transpile](https://github.com/bytecodealliance/jco#transpile) and calling existing Node-compatible APIs), but a more-optimized C++ native binding could be transparently swapped in in the future as motivated by usage and performance from Preview 2 feedback.
Rather than just fixing "Node and Node-compatible runtime" in the Portability Criteria, this PR does …
=> Change the portability criteria

proxy.md, wit/types.wit
This is a leftover artifact from recent refactorings but now that it's using a `duration` type which holds its value in nanoseconds the `-ms` suffix is no longer required.
Closes #78
=> Drop `-ms` suffix for request options

proxy.md, wit/types.wit
Modify the signature of `future-trailers.get` to more closely the other `future-` resources, returning a result at most once. This gives implementations the flexibility to transfer ownership of the resulting `trailers` out of the `future-trailers` resource.
=> Change future-trailers.get to produce at most one success

proxy.md, wit/types.wit
It's not currently possible to test whether a `field-key` is present in a `fields`, as our return value of an empty list could mean either that the header was missing, or had no value. Add the `fields.has` method to give an unambiguous way to test for `field-key` presence in a `fields`.
Fixes #82
=> Add `fields.has` 

proxy.md, wit/types.wit
Change the parameter names from `ms` to `duration` for the timeout setting methods of the `request-options` resource.
=> Change `ms` params to `duration`

.github/workflows/main.yml, imports.md, wit/proxy.wit
This PR factors out the imported APIs of http proxy to its own world, following the convention from other wasi proposals (e.g. https://github.com/WebAssembly/wasi-cli/blob/main/wit/imports.wit). 
The intention of the `wasi:http/imports` world is to be `include`d into other worlds such as `wasi:http/proxy` and `wasi:cloud-core/imports`.
Suprisingly, I wasn't expecting there to be such a huge change to the markdown files. It seems like part of the reason is that the imported interfaces are unordered?
=> refactor the imports to its own world

wit-0.3.0-draft/types.wit
This makes creating e.g. outbound GET requests easier and more efficient.
=> [0.3.0-draft] make {request|response} body optional

wit-0.3.0-draft/types.wit
This saves the user from having to use `get` followed by `delete` if they want access to the values they're removing.
=> [0.3.0-draft] add `fields.get-and-delete`

imports.md, proxy.md, wit/proxy.wit
This changes the `wasi:clocks` `include` statement to individual `import` statements in `wasi:http/proxy`. This came out of a conversation with @sunfishcode yesterday, who pointed out that if we're going to add timezones to `wasi:clocks` (https://github.com/WebAssembly/wasi-clocks/pull/61), `wasi:http/proxy` may not actually want to provide timezone support.
By switching from a catch-all `include` to individual `import` statements, we can decide later whether this is something we'd like to include. But conservatively we can start with the assumption that we won't.
This has some precedent in how we're handling our re-exports of `wasi:cli`: `wasi:http/proxy` includes `wasi:cli/stdin` and `wasi:cli/stdout` - but it does for example not include support for files or sockets.
=> Change `wasi:clocks` from `include` to `import` in `wasi:http/proxy`

imports.md, proxy.md, wit-0.3.0-draft/types.wit, wit/types.wit
The existing wording refers to a "request's authority", which is not clearly defined by HTTP specs.
This rewords it to refer to the "request's target URI authority" - the "authority" part of the "target URI" of the request, which is well-defined: https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#target.resource
Also normalize some word casing to match the HTTP Semantics doc.
=> Update request authority documentation

.github/workflows/main.yml, imports.md, proxy.md, wit-0.3.0-draft/types.wit, wit/types.wit
Closes #107.
This deprecates `field-key` in favor of `field-name` using the `@deprecated` attribute in WIT. This is the first deprecation we're running in WASI, making this the first field test of it in our tooling. The way I've implemented the type change is by doing the following:
```wit
type field-name = field-key;
type field-key = string;
```
I don't know WIT's type system well enough to know whether I could instead just have written:
```wit
type field-name = string;
```
This PR also catches a case for #117 that #121 missed: only the `0.3.0-draft` APIs had their prose text updated about casing. That seemed to be on accident - and since we're touching the `field-key` API's text anyway, that seemed like something easy to include here.
Thanks!
=> Deprecate `field-key` in favor of `field-name`

imports.md, proxy.md, wit-0.3.0-draft/types.wit, wit/types.wit
Put angle brackets around URLs in documentation, to help documentation tools like cargo doc generate clickable links for them.
=> Enclose URLs in documentation with angle brakcets.

.github/workflows/main.yml, wit/types.wit
This allows a server to send zero or more HTTP 1xx responses prior to sending the final response using `response-outparam.set`.
Note that this does not include support for consuming informational responses for outbound requests (which would be required to losslessly proxy such requests).
=> add `response-outparam.send-informational`

wit-0.3.0-draft/types.wit
Remove `wasi:io` usage in `wit-0.3.0-draft`
Followed the same stream error handling convention as currently in
- https://github.com/WebAssembly/wasi-filesystem/pull/164
- https://github.com/WebAssembly/wasi-sockets/pull/111
=> feat(0.3): rework stream error handling/remove `wasi:io` usage

wit-0.3.0-draft/types.wit
This commit changes wasi:http/types#body.finish to forward the optionally present trailers, rather than retrieve them with the possibility of generating an error along the way.
With this change, callers of `body.finish` will have to retreive trailers on their own, which *may* produce an efficiency gain in the case where trailers are present but not needed, and avoiding work of checking for trailers in the first place.
As this is a WASI p3 feature (for which work is ongoing in the [wasip3-prototyping repository](https://github.com/bytecodealliance/wasip3-prototyping)), you can "preview" the effects of this change on the implementation [in the PR there](https://github.com/bytecodealliance/wasip3-prototyping/pull/16).
=> feat: allow independent retrieval of trailers

wit-0.3.0-draft/types.wit
Refs #154 
Retrieving trailers implies reading the body of the response, which is a fallible operation.
Currently, guests that call `finish` without calling `stream` first have no way to acquire the `error-code` that the operation might have failed with (due to the implicit read of the body). Even in cases where the data frames of the body might have been fully read before calling `finish`, reading of the trailers can potentially still fail.
=> feat(p3): allow trailer retrieval to fail

wit-0.3.0-draft/types.wit
Currently, there's no way to acquire the owned `request-options` from the `request`, return them as part of the `into-parts` along the other moved resources
=> feat(p3): return owned `request-options` on consumption

wit-0.3.0-draft/types.wit
- Make bodies non-optional for request and response constructors
- Take a `future<result<option<trailers>, error-code>>` parameter in request/response constructors (refs https://github.com/WebAssembly/component-model/issues/474#issuecomment-2736430031)
- Report any transmit errors occurring in the future returned by request/response constructor
- Allow `headers` resources acquired by calling `request.headers` or `response.headers` to persist *after* respective `into-parts` is called, referencing the immutable headers of the original request/response. This implies that the `headers` acquired this way are not, if fact, children of the original request/response they originated from and the original request/response can be freely dropped and/or moved even before they are dropped.
- Do not …
=> [v0.3] model bodies after `stream<u8, trailers, error-code>`, trap less

wit-0.3.0-draft/types.wit
https://github.com/WebAssembly/wasi-clocks/pull/98 split the `duration` type out into its own file, which can be imported directly instead of needing to reach into the `monotonic` package. This is [already pulled in to the deps](https://github.com/WebAssembly/wasi-http/blob/ce36dac529d5def9e5191dd624e928eb12325111/wit-0.3.0-draft/deps/clocks/types.wit) so should be usable here.
=> use new clocks/types.{duration} instead of clocks/monotonic
